### ISSUE TITLE
Symbolication: Missing DSYM File (All Errors)

### ISSUE THREAD

**Issue by kpujjigit** [sentry-demos/ios#30]
Example Issue: https://testorg-az.sentry.io/issues/4263051342/events/741e32109c914b998bba985264398347/?project=6249899

**Problem:** While Debug Symbol upload appears to succeed locally according to log output, some events from the iOS demo are missing important symbol files and therefore not symbolicating.

**Goal:** Ensure all symbols reach the testOrg in order to fully symbolicate the events.

I will post more examples/context as observation continues.

**Comment by realkosty** [comment]
This is a regression. It used to work. Not sure what changed.

**Comment by armcknight** [comment]
I wonder if this will fix the issue: https://sentry.slack.com/archives/C010884QHLG/p1695307981879539

**Comment by armcknight** [comment]
Fixed in #46
