### ISSUE TITLE
✨ iOS - SE <> ENG TaskList ✨

### ISSUE THREAD

**Issue by kpujjigit** [sentry-demos/ios#32]
List of action items to improve Sentry's iOS Demo (EmpowerPlants):

- [x] https://github.com/sentry-demos/ios/issues/30
- [ ] https://github.com/sentry-demos/ios/issues/33
- [x] https://github.com/sentry-demos/ios/issues/25
- [x] https://github.com/sentry-demos/ios/issues/26
- [x] https://github.com/sentry-demos/ios/issues/27
- [x] https://github.com/sentry-demos/ios/issues/28
- [ ] https://github.com/sentry-demos/ios/issues/29
- [ ] https://github.com/sentry-demos/ios/issues/23
- [ ] https://github.com/sentry-demos/ios/issues/24
- [ ] https://github.com/sentry-demos/ios/issues/31
- [x] https://github.com/sentry-demos/ios/issues/42

**Comment by armcknight** [comment]
Update, some prs for the perf/profiling issues:
- #25: #39 
- #26: #63 
- #27: #62 
- #28: #61

**Comment by armcknight** [comment]
I'm also going to add this profiling issue type: https://github.com/sentry-demos/ios/issues/64
