### ISSUE TITLE
Distributed Tracing Regression - Missing Backend Error in Full Trace View

### ISSUE THREAD

**Issue by kpujjigit** [sentry-demos/ios#74]
The Full Trace View does not yet link to the backend Flask error that is invoked as part of the iOS Demo's Flagship Error.

Example from Flagship Error: https://demo.sentry.io/issues/4221692556/?project=6249899

(Currently only seeing the backend Transaction in addition to the mobile error)
<img width="1456" alt="image" src="https://github.com/sentry-demos/ios/assets/103009467/dbc0bcf9-d6d0-40e2-b0f6-554f37127279">

**Comment by kahest** [comment]
@kpujjigit Seems to work (again?), see e.g. [here](https://demo.sentry.io/performance/trace/fa9ad615a1fd48b3be6cc27559de80f2/?limit=100&pageEnd=2023-12-20T04%3A29%3A20.692&pageStart=2023-12-19T04%3A29%3A20.692). I checked the last 20 or so instances by selecting "Latest" event and navigating back one by one - everyone had 5 events in the trace with 2 tx and 2 issues.
Compare to "Oldest" event from Sept 20 which is missing the backend error.

**Comment by realkosty** [comment]
@kpujjigit Suspect commits have been always brittle. Next time let's immediately raise this in `#discuss-issues` and get to the bottom of it. In my experience usually it has nothing to do with SDK/client-side.

**Comment by kpujjigit** [comment]
@kahest - This is resolved, issue was on the Flask side. See more here - https://github.com/sentry-demos/empower/pull/366

**Comment by kpujjigit** [comment]
> @kpujjigit Suspect commits have been always brittle. Next time let's immediately raise this in `#discuss-issues` and get to the bottom of it. In my experience usually it has nothing to do with SDK/client-side.

@realkosty just verifying this comment is in the right spot? This GH Issue concerns Dist. Tracing, not Suspect Commits; those are still broken.
